# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: numero.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnumero.proto\"\x12\n\x10RequisicaoNumero\"\x1f\n\rRepostaNumero\x12\x0e\n\x06numero\x18\x01 \x01(\x05\x32<\n\x06Numero\x12\x32\n\x0bObterNumero\x12\x11.RequisicaoNumero\x1a\x0e.RepostaNumero\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numero_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUISICAONUMERO']._serialized_start=16
  _globals['_REQUISICAONUMERO']._serialized_end=34
  _globals['_REPOSTANUMERO']._serialized_start=36
  _globals['_REPOSTANUMERO']._serialized_end=67
  _globals['_NUMERO']._serialized_start=69
  _globals['_NUMERO']._serialized_end=129
# @@protoc_insertion_point(module_scope)
